/* eslint-disable */
// @generated by protobuf-ts 2.8.2 with parameter ts_nocheck,eslint_disable
// @generated from protobuf file "error.proto" (package "wirepas.proto.gateway_api", syntax proto2)
// tslint:disable
// @ts-nocheck
/**
 * @generated from protobuf enum wirepas.proto.gateway_api.ErrorCode
 */
export enum ErrorCode {
	/**
	 * @generated from protobuf enum value: OK = 0;
	 */
	OK = 0,
	/**
	 * @generated from protobuf enum value: INTERNAL_ERROR = 1;
	 */
	INTERNAL_ERROR = 1,
	/**
	 * @generated from protobuf enum value: INVALID_SINK_ID = 2;
	 */
	INVALID_SINK_ID = 2,
	/**
	 * @generated from protobuf enum value: INVALID_ROLE = 3;
	 */
	INVALID_ROLE = 3,
	/**
	 * @generated from protobuf enum value: INVALID_NETWORK_ADDRESS = 4;
	 */
	INVALID_NETWORK_ADDRESS = 4,
	/**
	 * @generated from protobuf enum value: INVALID_NETWORK_CHANNEL = 5;
	 */
	INVALID_NETWORK_CHANNEL = 5,
	/**
	 * @generated from protobuf enum value: INVALID_CHANNEL_MAP = 6;
	 */
	INVALID_CHANNEL_MAP = 6,
	/**
	 * @generated from protobuf enum value: INVALID_NETWORK_KEYS = 7;
	 */
	INVALID_NETWORK_KEYS = 7,
	/**
	 * @generated from protobuf enum value: INVALID_AC_RANGE = 8;
	 */
	INVALID_AC_RANGE = 8,
	/**
	 * @generated from protobuf enum value: INVALID_SINK_STATE = 9;
	 */
	INVALID_SINK_STATE = 9,
	/**
	 * @generated from protobuf enum value: INVALID_DEST_ADDRESS = 10;
	 */
	INVALID_DEST_ADDRESS = 10,
	/**
	 * @generated from protobuf enum value: INVALID_DEST_ENDPOINT = 11;
	 */
	INVALID_DEST_ENDPOINT = 11,
	/**
	 * @generated from protobuf enum value: INVALID_SRC_ENDPOINT = 12;
	 */
	INVALID_SRC_ENDPOINT = 12,
	/**
	 * @generated from protobuf enum value: INVALID_QOS = 13;
	 */
	INVALID_QOS = 13,
	/**
	 * @generated from protobuf enum value: INVALID_DATA_PAYLOAD = 14;
	 */
	INVALID_DATA_PAYLOAD = 14,
	/**
	 * @generated from protobuf enum value: INVALID_SCRATCHPAD = 15;
	 */
	INVALID_SCRATCHPAD = 15,
	/**
	 * @generated from protobuf enum value: INVALID_SCRATCHPAD_SIZE = 16;
	 */
	INVALID_SCRATCHPAD_SIZE = 16,
	/**
	 * @generated from protobuf enum value: INVLAID_SEQUENCE_NUMBER = 17;
	 */
	INVLAID_SEQUENCE_NUMBER = 17,
	/**
	 * @generated from protobuf enum value: INVALID_REBOOT_DELAY = 18;
	 */
	INVALID_REBOOT_DELAY = 18,
	/**
	 * @generated from protobuf enum value: INVALID_DIAG_INTERVAL = 19;
	 */
	INVALID_DIAG_INTERVAL = 19,
	/**
	 * @generated from protobuf enum value: INVALID_APP_CONFIG = 20;
	 */
	INVALID_APP_CONFIG = 20,
	/**
	 * @generated from protobuf enum value: INVALID_PARAM = 21;
	 */
	INVALID_PARAM = 21,
	/**
	 * @generated from protobuf enum value: NO_SCRATCHPAD_PRESENT = 22;
	 */
	NO_SCRATCHPAD_PRESENT = 22,
	/**
	 * @generated from protobuf enum value: ACCESS_DENIED = 23;
	 */
	ACCESS_DENIED = 23,
	/**
	 * @generated from protobuf enum value: REQUEST_NEEDS_SINK_ID = 24;
	 */
	REQUEST_NEEDS_SINK_ID = 24,
	/**
	 * @generated from protobuf enum value: INVALID_MAX_HOP_COUNT = 25;
	 */
	INVALID_MAX_HOP_COUNT = 25,
}
